export default Object.freeze({
  'Bali': true,
  'Kenya': true,
  'California': true,
  'New york': true,
  'Texas': true,
  'Iceland': true,
  'Greece / Rome': true,
  'Italy': true,
  'Portugal': true,
  'Korea': true,
  'Tokyo': true,
  'Singapore': true,
  'Malaysia': true,
  'London': true,
  'Germany': true,
  'France': true,
  'Switzerland': true,
  'Keck Observatory, Hawaii': true,
  'Amsterdam': true,
});
